#Kabanero! on activate substitute Digest for text '@Digest@'
apiVersion: tekton.dev/v1alpha1
kind: Pipeline
metadata:
  name: build-deploy-pl-@Digest@
spec:
  params:
  - name: event-type
    type: string
    description: "The event type"
  - name: event-ref
    type: string
    description: "The event ref"
  - name: docker-imagename
    type: string
  - name: docker-imagetag
    type: string
  resources:
  - name: git-source
    type: git
  - name: docker-image
    type: image
  tasks:
  - name: utilities-task
    taskRef:
      name: utilities-task-@Digest@
    params:
      - name: docker-imagename
        value: "$(params.docker-imagename)"
      - name: docker-imagetag
        value: "$(params.docker-imagetag)"
    resources:
      inputs:
      - name: git-source
        resource: git-source
      - name: docker-image
        resource: docker-image
      outputs:
      - name: git-source
        resource: git-source
  - name: build-push-task
    taskRef:
      name: build-push-task-@Digest@
    runAfter: [utilities-task]
    resources:
      inputs:
      - name: git-source
        resource: git-source
        from: [utilities-task]
      outputs:
      - name: docker-image
        resource: docker-image
      - name: git-source
        resource: git-source
  - name: image-scan-task
    taskRef:
      name: image-scan-task-@Digest@
    runAfter: [build-push-task]
    resources:
      inputs:
      - name: git-source
        resource: git-source
        from: [utilities-task]
      - name: docker-image
        resource: docker-image
  - name: deploy-task
    conditions:
    - conditionRef: deployment-condition-@Digest@
      params:
      - name: event-type
        value: $(params.event-type)
      - name: event-ref
        value: $(params.event-ref)
    taskRef:
      name: deploy-task-@Digest@
    runAfter: [image-scan-task]
    resources:
      inputs:
      - name: git-source
        resource: git-source
        from: [build-push-task]
      - name: docker-image
        resource: docker-image
